name: "Build"
on: 
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
    - uses: actions/checkout@v3
    - name: Install Java 12
    - run: |
        npm i
        npm run all
        with
        distribution: 'zulu'
        java-version: '12'
        - name: 'Cache Bazel files'
        uses: actions/cache@v3
        with
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-build-${{ github.sha }}
        restore-keys: |
        ${{ runner.os }}-bazel-build-
        - name: Build maven artifacts
        run: bazelisk build //:axt_m2repository
        shell: bash
        - name: cp to upload dir
        run: |
        mkdir -p ~/download
        cp bazel-bin/axt_m2repository.zip ~/download
        shell: bash
        - name: 'Upload local snapshot for tests'
        uses: actions/upload-artifact@v3
        with:
        name: local-snapshot
        path: ~/download
        - name: 'Clean bazel cache'
        rm -rf $(bazel info repository_cache)
        rm -rf ~/.cache/bazel/*/*/external/
        test:
        shell: bash
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
        - name: Check out repository code
        uses: actions/checkout@v3
        - name: Install Java 12
        uses: actions/setup-java@v3
        with:
        
    
